name: Tests on dev branch
on:
  pull_request:
    branches: [ dev ]
    types: [ opened, synchronize ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm t